### PR TITLE
Merge of SWING status flag - Feature/1277 into develop

### PR DESCRIPTION
**Pull request by ftuffner**
#### What's this Pull Request do?
Adds a status flag to determine when a SWING_PQ or SWING is truly behaving as an infinite bus.

#### Where should the reviewer start?
Pull the code, compile it, run it.

#### How should this be tested?
Just an informational flag.  All autotests should pass.  Check test_multi_island_SWING_PQ_Indep_Islands.glm for an example

#### What are the relevant issues?
#1277

### CODE REVIEW

**Review by afisher1 — COMMENTED** [review]
I can't find where swing_functions_enabled ever gets set to true. Was it done in the NR_busdata and used internally and not captured by the class and you are just exposing it to the node and triplex_node?

**Comment by ftuffner** [comment]
Effectively.  It's primarily set in `fault_check` during topology reconfiguration/checks.  It's really only used in solver_nr.cpp to determine how to handle `SWING` or `SWING_PQ` buses - the flag was mostly if you have multiple `SWING_PQ` on a topology to easily figure out which one `fault_check` decided was the topological `SWING` node.

**Comment by afisher1** [comment]
Then I'm good with the changes. Nothing seems broken autotest wise so I'm gonna merge it here.

**Comment by afisher1** [comment]
merging

**Pull request merged**
