### PR TITLE
Fix invalid lock causing read lock timeout in IEEE 8500

### LINKED ISSUE #1208: Ubuntu throws a "read lock timeout" error when running an IEEE 8500-node system
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
When running the 8500-node system from tools/IEEE Test Models/8500node under Ubuntu (18.04 and 19.10), it fails with a "read lock timeout" error.  This does not occur on Windows, nor does it seem to happen in /develop (but another issue interferes there).

## Please provide the steps to reproduce.
Generate the 8500-node system, per the notes in #1206, then run it under Ubuntu.  It should fail at the start of execution with a "read lock timeout" error.

## Please provide the exact error/warnining/failure message printed on the console.
From #1206, but verified on my end as well:

    WARNING  [INIT] : object name '1515A' does not follow strict naming rules and may not link correctly during load time
    WARNING  [INIT] : last warning message was repeated 156 times
    WARNING  [INIT] : Daylight saving time (DST) is not handled correctly when using TMY2 datasets; please use TMY3 for DST-corrected weather data.
    WARNING  [INIT] : waterheater::init() : height and diameter were not specified, defaulting to 3.78 ft
    ERROR    [2000-09-01 12:00:00 PDT] : exec halted: read lock timeout
    FATAL    [2000-09-01 12:00:00 PDT] : shutdown after simulation stopped prematurely
    FATAL    [2000-09-01 12:00:00 PDT] : environment startup failed: Success

## If possible, please provide any screenshots and other supporting information.
See #1206 discussions for some additional detail.

-------------------------------------------------------------------------------------------------------------

### PR DESCRIPTION
**Pull request by eberleim**
#### What's this Pull Request do?
Resolves #1208 

#### How should this be tested?
Verify IEEE 8500 and related tests do not fail

### CODE REVIEW

**Comment by esilksel** [comment]
Just to comment, it appears that the 8500 node system runs without issue on my machine on the bugfix/1208 branch. Going to see if we can have someone verify the "correctness" of the results as well.

**Comment by ftuffner** [comment]
@esilksel We believe this fixes #1208, but it needs a little more verification.  Mostly because I'm curious why it is failing in the 8500-node, but autotests that should have a similar setup are working fine.  It's on the list of things to look into this week.

**Comment by esilksel** [comment]
Yes, good that you're trying to root-cause it. We appreciate it! :D

**Comment by dchassin** [comment]
I don't think that's the correct fix.  I think you want `READ(UN)LOCK_OBJECT(Rlink->my())`.  However, doing this results in an assert failure on the voltage in two of the autotests.

**Comment by eberleim** [comment]
@dchassin structures of type `OBJECT*` do not appear to support a `->my()` invocation on my platform, can you verify if this is SLAC/PNNL divergent behavior, or if there is a special configuration under which you are compiling?

**Comment by dchassin** [comment]
The result shouldn't be different but it's possible the semantics have changed in a some subtle way on SLAC's version.  In any case `RLink` is a class which always follows the header without a vtable (yuk!).  The semantic of `my()` is simply `((OBJECT*)RLink)-1)` (again--yuk).  You can try that directly.  It's basically what `OBJECTHDR(RLink)` is supposed to do (but apparently doesn't) in this case. In any case, `RLink->lock` will never be correct, even if the class implements a `lock` variable because other `rlock` calls won't lock the same memory and collisions may occur.

I'm more interested in the fact that when READLOCK is pointed to the correct lock variable, the result of the test is different.  This suggests that when locking correctly `calculate_power()` behaves differently.  That worries me a lot because (1) the basic test has no parallelism so locking shouldn't matter, and (2) even if it did, the locking system should prevent collision updates.  Perhaps the test reference player was generated from a faulty run and it should be checked by a power systems engineer before it is used for validation.

**Comment by dchassin** [comment]
Here's an interesting tidbit: `link_object::calculate_power()` has a READLOCK on the `to` object.  I wonder if this is deadlocking with `capacitor`'s `PC_AUTOLOCK` setting?

**Comment by eberleim** [comment]
@dchassin To validate, I attempted to re-lock the lock on RLink immediately after locking it, and can verify that it produces a readlock timeout. It's possible the behavior with `RLink->lock` not consistently locking the same lock has been resolved, leading to this issue.

**Comment by dchassin** [comment]
@eberleim, ok, I see how the two versions differ now. The type of `RLink` has changed from `class link_object*` to `OBJECT*`. So you're right that `RLink->object` is the correct lock. 

Nonetheless, I think the `link_object` takes out a read lock on the `to` object during `calculate_power()`. The `to` object might be the capacitor that just called `update_power_pwr_object` while processing a sync event and may have automatically taken out a write lock on itself .  This could cause a dead lock.

**Comment by ftuffner** [comment]
I'm a bit late getting to this.  The issue @dchassin brought up is valid, and would most likely happen with FBS systems.  Added a check to prevent having the remote_sense point to a link that has the capacitor as its `to` end.

**Comment by ftuffner** [comment]
Unable to fully reconcile why the previous OBJECTHDR inclusion wasn't causing issues earlier.  Code is correct now, but not sure why it wasn't causing issues earlier.  My only guess is that the pointer offset was still on a property and manipulating it, but it either "coincidentally" aligned with the lock property, or more likely, it was tweaking a part of the object memory that just wasn't critical/noticed.

**Pull request merged**
