### PR TITLE
Feature/manual 1024 merge

### PR DESCRIPTION
**Pull request by afisher1**
#### What's this Pull Request do?
This PR adds the HELICS federate functionality to GridLAB-D. This allows a GridLAB-D model to participate in a HELICS co-simulation as a single federate. The PR also provides changes so that GridLAB-D can be compiled using MSYS2 for windows binaries. This PR will most likely not build on the old mingw/msys set up we have for GridLAB-D.
#### Where should the reviewer start?
The reviewer should review the files that were changed and verify the PR doesn't break the build or autotests.
#### How should this be tested?
it should be tested on at least Linux and Windows.
#### What are the relevant issues?
#1024 

- [ ] Does this add new dependencies?
It adds new optional dependencies: FNCS and HELICS and adds MSYS2 dependency for compiling on Windows.
- [ ] Is there appropriate logging included?
Yes? I should probably remove this from the template as this is nebulous.

### CODE REVIEW

**Comment by afisher1** [comment]
hmm I will take a look at this now.

**Comment by afisher1** [comment]
I accidentally closed this PR. I was able to reproduce the FNCS linking problem. I believe the FNCS and HELICS linking problems lies in the fact that the .dlls are in the bin folders. I'm going to remove the static libs and copy the .dlls in the lib folders. That worked for FNCS at least on my end.

**Comment by afisher1** [comment]
@ftuffner I've rearranged the files inside of the FNCS and HELICS tarballs. Can you give it another go. It was working on my end. Also, I completely forgot to add libzmq and boost libs that HELICS is compiled with in that tarball. I've added all that in so hopefully it works.

**Comment by ftuffner** [comment]
@afisher1 Those updates look like they fixed it.  I was able to build GLD with FNCS and HELICS enabled using those files.  I wasn't able to test the actual interfacing with FNCS or HELICS, but the build process works and all autotests still pass.  This appears ready to merge in, if we're ready.

**Comment by ftuffner** [comment]
All compiling options seem to work fine.  All autotests pass under Windows and Linux (aside from the MySQL ones documented in a separate issue).  Updated instructions are in the pull request and the Wiki is expected to be updated soon.  Merging this in.

**Pull request merged**
