### PR TITLE
(#1220) Implement ability to dump rhs of matrix equations for use in external programs

### PR DESCRIPTION
**Pull request by ftuffner**
### What's this Pull Request do?
Updates the matrix output methods in NR to include the RHS information

#### Where should the reviewer start?
Compile the code and run an example, such at powerflow/test_NR_matrix_dump.glm.  Make sure "NR_matrix_output_rhs" is true and hit enter.

#### How should this be tested?
Run the GLM above with teh "NR_matrix_output_rhs" set, and see if the output file reflect thta.

#### Any background context you want to provide?
Similar to legacy #992, but that code is really old (and does something slightly different)

#### What are the relevant issues?
N/A

#### Questions:
- [X] Does this add new dependencies?
- [X] Is there appropriate logging included?

### CODE REVIEW

**Comment by kadecornelison** [comment]
I got the below errors when running make. I believe this is due to a newer version of MatLab that I am using. 

In file included from gldcore/link/matlab/matlab.cpp:23:
gldcore/link/matlab/matlab.cpp: In function 'mxArray* matlab_create_value(gld_property*)':
C:/Program Files/MATLAB/R2019B/extern/include/matrix.h:482:17: error: 'mxGetPiIsDeprecated' was not declared in this scope
  482 | #define mxGetPi mxGetPiIsDeprecated
      |                 ^~~~~~~~~~~~~~~~~~~
gldcore/link/matlab/matlab.cpp:86:5: note: in expansion of macro 'mxGetPi'
   86 |    *mxGetPi(value) = v->Im();
      |     ^~~~~~~
gldcore/link/matlab/matlab.cpp: In function 'mxArray* matlab_set_value(mxArray*, gld_property*)':
C:/Program Files/MATLAB/R2019B/extern/include/matrix.h:482:17: error: 'mxGetPiIsDeprecated' was not declared in this scope
  482 | #define mxGetPi mxGetPiIsDeprecated
      |                 ^~~~~~~~~~~~~~~~~~~
gldcore/link/matlab/matlab.cpp:157:16: note: in expansion of macro 'mxGetPi'
  157 |    double *i = mxGetPi(value);
      |                ^~~~~~~
gldcore/link/matlab/matlab.cpp: In function 'mxArray* matlab_get_value(mxArray*, gld_property*)':
C:/Program Files/MATLAB/R2019B/extern/include/matrix.h:482:17: error: 'mxGetPiIsDeprecated' was not declared in this scope
  482 | #define mxGetPi mxGetPiIsDeprecated
      |                 ^~~~~~~~~~~~~~~~~~~
gldcore/link/matlab/matlab.cpp:228:16: note: in expansion of macro 'mxGetPi'
  228 |    double *i = mxGetPi(value);
      |                ^~~~~~~
make[1]: *** [Makefile:4949: gldcore/link/matlab/glxmatlab_la-matlab.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
  CXX      gldcore/solvers/glsolvers_la-modified_euler.lo
make[1]: Leaving directory '/c/Code/gridlabd/gridlab-d'
make: *** [Makefile:1906: all] Error 2

**Comment by ftuffner** [comment]
@kadecornelison The MATLAB error is quite likely related to how they restructured the interface in r2018+.  See http://gridlab-d.shoutwiki.com/wiki/Building_GridLAB-D_on_Windows_with_MSYS2#Building_with_the_MATLAB_Link, namely the part about adding the `-DMATLAB_DEFAULT_RELEASE=R2017b` to `CFLAGS` and `CXXFLAGS` (really may only be needed in `CXXFLAGS`).

**Comment by kadecornelison** [comment]
@ftuffner  Thanks for the information. I will try building it with the flags.

**Comment by kadecornelison** [comment]
Pulled down the latest after Frank merged in develop. Everything worked as expected.

**Pull request merged**
