### PR TITLE
Feature/1330 merge into develop branch to support TAP-API Integration

### PR DESCRIPTION
**Pull request by BilalAhmad-Bhatti**
#### What's this Pull Request do?
Implements the following functionality for the wind turbine model:
-Specification of wind speed from player files. With the merge of this feature branch, the user would be able to specify wind speed using i) Climate files, ii) player files, and iii) direct specification
-An autotest for validating TAP-API integration and the above-mentioned functionality
#### Where should the reviewer start?
Files windturb_dg.cpp and windturb_dg.h in gridlab-d/generators
#### How should this be tested?
The autotest "test_windturbine_ws_conversions.glm" tests the new functionality
#### Any background context you want to provide?
These changes are made to support TAP-API integration (MIRACL deliverable for Q2 FY22)
#### Screenshots (if appropriate)
Attached is the autotest validation results
[validate.txt](https://github.com/gridlab-d/gridlab-d/files/8345952/validate.txt)
#### Questions:
- [ ] Does this add new dependencies?
- [x] Is there appropriate logging included?

### CODE REVIEW

**Comment by ftuffner** [comment]
@BilalAhmad-Bhatti - Looks good overall.  A couple questions on the code:

- Are the two published properties (though they are the same thing) at windturb_dg.cpp:110 supposed to be commented?  Or were they meant to be `PA_HIDDEN` properties for debugging?
- The comments around windturb_dg.cpp:182 confuse me a little.  It says the reference height is 10 m, but the next comment says something about a 37 m height (even though the value is 10).  I think I'm missing something here.

**Comment by BilalAhmad-Bhatti** [comment]
Hi Frank,
Here is the response:

  *   They are supposed to be commented. I do not see much value from the debugging perspective
  *   Line 182 is default wind speed (8 m/s) at the reference (10 m) height. Line 183 is wind speed (10 m/s) at hub height (37 m is the default hub height). We used equation on line 1219 for this conversion between default wind speeds.

Let me know if you need additional info.

Thanks
Bilal

**Comment by ftuffner** [comment]
For the two commented inputs, is there any objection to just deleting them then?  Unless it has a very clear "this is a future change planned" type of thing, it may be good to just remove them.

**Comment by BilalAhmad-Bhatti** [comment]
Yes. Please go ahead and delete them !!

Thanks
Bilal

**Review by ftuffner — APPROVED** [review]

**Pull request merged**
