### PR TITLE
Merge of Portland State HPWH model

### PR DESCRIPTION
**Pull request by ftuffner**
#### What's this Pull Request do?
Merges in the updated/functional heat pump water heater model submitted by Portland State/Midrar Adham.
#### Where should the reviewer start?
Pull, compile, examine the outputs of the new `test_heatpump_waterheater.glm`
#### How should this be tested?
Verify the new water heater model has reasonable temperature regulation (no more going massively out of bounds).
#### What are the relevant issues?
#1123 
#### Screenshots (if appropriate)
N/A
#### Questions:
- [ ] Does this add new dependencies?
- [ ] Is there appropriate logging included?

### CODE REVIEW

**Comment by trevorhardy** [comment]
@ftuffner, I'm getting an error on that autotest:

```
ERROR    [2021-12-25 23:06:00 PST] : Assert failed on wh1: temperature 115.196 not within 0.100000 of given value 116.013
``

**Comment by trevorhardy** [comment]
I should note that I'm testing on my Mac using clang but I did do a clean build.

**Comment by ftuffner** [comment]
Passes on Windows, but fails in two different spots on Linux and Mac.

**Review by trevorhardy — APPROVED** [review]
Autotest passes.

**Pull request merged**
