### PR TITLE
added developed hpwh model

### PR DESCRIPTION
**Pull request by MidrarAdham**
#### What's this Pull Request do?

This pull request adds a Heat Pump Water Heater (HPWH) model to GridLAB-D source code.

#### Where should the reviewer start?

Clone the branch named "dev_hpwh_model". Two files were modified and are located within the residential folder. The files are "waterheater.cpp" and "waterheater.h". The reviewers may start from "waterheater.cpp" file, line 992. The HPWH model is wrapped in a function named "sync_energytake".  

#### How should this be tested?

The HPWH model maybe tested by including a waterheater object within a glm file and define the waterheater object "heat_mode" property as "HEAT_PUMP".  A Testing file and instructions are available in [this link](https://github.com/PortlandStatePowerLab/gridlabd_hpwh_model_PSU).

#### Any background context you want to provide?

An approved Master's thesis associated with the HPWH model will be shared once its published. For now, a brief background is available in [this link](https://github.com/PortlandStatePowerLab/gridlabd_hpwh_model_PSU/blob/main/README.md).

#### What are the relevant issues?

The HPWH object did not behave properly. The tank temperature seemed to be randomly changing regardless of the HPWH status (ON/OFF). A discussion is available on [SourceForge](https://sourceforge.net/p/gridlab-d/discussion/842562/thread/4a543d83a0/?limit=25#941c) and an issue was created on [GitHub](https://github.com/gridlab-d/gridlab-d/issues/1123).

#### Questions:
- [ ] Does this add new dependencies?
    - No.
- [ ] Is there appropriate logging included?
    - Yes.

### CODE REVIEW

**Comment by ftuffner** [comment]
@MidrarAdham  Do you have an example file for this?  I've used an older one to evaluate it, but the output looks a bit odd, so I may not have parameters correct.

**Comment by MidrarAdham** [comment]
@ftuffner apologize for the late response, I was out for a conference. Once the waterheater.cpp and waterheater.h [waterheater_cpp_h_files.zip](https://github.com/gridlab-d/gridlab-d/files/9183942/waterheater_cpp_h_files.zip) files are placed in the residential folder and the gridlab-d is compiled, the HPWH object should work. Here is a simple glm file that has a HPWH object [hpwh_testing_example.zip](https://github.com/gridlab-d/gridlab-d/files/9183755/hpwh_testing_example.zip). Would mind sharing the model you're using to test the HPWH object? I can modify the source code further, If need be, to get the model you're using running.

**Comment by ftuffner** [comment]
@MidrarAdham I was using the one located in #1123, so it may not have properly matched.  I'll try your new example and get back to you.

**Comment by ftuffner** [comment]
@MidrarAdham Is there any write-up or more detailed information available for this model?  In particular, some of the constants could really use some further justification/explanation (e.g., the `heating_element_capacity` variables and `compressor_max_threshold`).  There are some mentions about a curve fit, but if further information can be provided, that would be useful.

**Comment by ftuffner** [comment]
Due to the develop update, this has basically be paralleled with bugfix/1123 (associated with #1123) to keep it cleaner.  Keeping this open for now, but changes will be pushed under a separate PR.

**Comment by ftuffner** [comment]
PR #1389 is the "proper develop" version of this PR.

**Comment by ftuffner** [comment]
Merged into separate pull request #1389 (due to code rebasing).

**Comment by MidrarAdham** [comment]
> @MidrarAdham Is there any write-up or more detailed information available for this model? In particular, some of the constants could really use some further justification/explanation (e.g., the `heating_element_capacity` variables and `compressor_max_threshold`). There are some mentions about a curve fit, but if further information can be provided, that would be useful.

Hello frank, 

Apologize for the late reply. I updated the original post for this PR. In the answer for the question 

> Any background context you want to provide?

, I linked two files. One that explains the development process for this model and a README file that summarizes  some variable definitions.

**Pull request closed without merging**
