### PR TITLE
Task/1288

### PR DESCRIPTION
**Pull request by trevorhardy**
#### What's this Pull Request do?
Pulls in changes from task #1288 (removal of v5.0 deprecated parameters)

#### Where should the reviewer start?
No particular place

#### How should this be tested?
@trevorhardy has already tested these changes with autotest where they all passed.

#### Any background context you want to provide?
Only parameters marked `PT_DEPRECATED` were removed from the codebase.

#### What are the relevant issues?
The changes to "triplex_node" (removing the ability to have a native load) will cause models to break as the load parameters are no longer a part of the "triplex_node" object. Once merged anybody building from "develop" and using such models will have problems.

#### Questions:
- Does this add new dependencies? - no
- Is there appropriate logging included? - no change to logging

### CODE REVIEW

**Review by afisher1 — COMMENTED** [review]
There was a conflict in inverter.cpp that I wasn't sure which one's correct. @ftuffner can you check the diff on inverter.cpp. other than that all autotests pass so I'm good with it.

**Comment by ftuffner** [comment]
@afisher1 Not seeing the conflict, but maybe I'm missing something?

@trevorhardy  Something I did notice is none of the variables were removed.  The published properties and code portions were adjusted, but the .h files still have "_deprecated" variables that could be removed.  The compiler _should_ handle everything, but it depends how much you trust it

**Comment by trevorhardy** [comment]
Let me take a crack at the .h files (probably this afternoon) before we merge this.

**Comment by trevorhardy** [comment]
OK, pulled the parameters out of the .h files. I think we're good to merge.

**Comment by ftuffner** [comment]
@trevorhardy There are some "not as clearly labeled" portions in triplex_node that still need removing (associated with the deprecated published properties being removed).  They are flagged by comment blocks with "deprecated" in the text.  Theoretically, they can just be deleted.  I can potentially take a look at it later this morning if they are getting a bit too far into the weeds.

**Comment by trevorhardy** [comment]
One of those code blocks is the entire "triplex_node::BOTH_triplex_sync_fxn()"; I'm assuming that's OK to pull?

**Comment by trevorhardy** [comment]
If I pull out that function (including its declaration) it appears to cause problems:

```
      triplex_load::inter_deltaupdate_triplex_load(unsigned long long, unsigned long, unsigned int, bool) in triplex_load.cpp.o
      triplex_meter::inter_deltaupdate_triplex_meter(unsigned long long, unsigned long, unsigned int, bool) in triplex_meter.cpp.o
      triplex_node::sync(long long) in triplex_node.cpp.o
      triplex_node::inter_deltaupdate_triplex_node(unsigned long long, unsigned long, unsigned int, bool) in triplex_node.cpp.o
ld: symbol(s) not found for architecture x86_64
```

This worries me; the function is referenced in other code and we're going to essentially make it a NOP?

**Comment by trevorhardy** [comment]
Autotests all pass with just a stub definition for "triplex_node::BOTH_triplex_sync_fxn()". Do we want to keep that stub in place or remove it and its references in the other "triplex_..." files?

**Comment by ftuffner** [comment]
@trevorhardy I'm a fan of just removing it, so I did (didn't notice that was all that was there).  Removed the deprecated/no-longer-needed header entries too.

@afisher1 Do you still have any concerns on this one?  It looks ready to merge to me.

**Review by ftuffner — APPROVED** [review]
All changes look reasonable and autotests all pass, so bonus!

**Comment by trevorhardy** [comment]
What are we waiting for on this, again? I think its ready to merge but maybe not? @ftuffner?

**Comment by ftuffner** [comment]
@trevorhardy I think it is ready, but you had @afisher1 and I both tagged for review and it didn't look like Andy had done it yet.  If so (or one review is good enough), then we can merge it in.

**Comment by trevorhardy** [comment]
My thanks for @ftuffner for getting this branch ready to commit by removing many blank lines (among other things.)

**Comment by trevorhardy** [comment]
I’ll take another crack, pull them out, and see how the autotests are doing.

Trevopr

From: Frank Tuffner ***@***.***>
Reply-To: gridlab-d/gridlab-d ***@***.***>
Date: Tuesday, August 30, 2022 at 9:27 AM
To: gridlab-d/gridlab-d ***@***.***>
Cc: "Hardy, Trevor D" ***@***.***>, Mention ***@***.***>
Subject: Re: [gridlab-d/gridlab-d] Task/1288 (PR #1353)

Check twice before you click! This email originated from outside PNNL.


@trevorhardy<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftrevorhardy&data=05%7C01%7Ctrevor.hardy%40pnnl.gov%7Cb4c72c9963f44dc2453008da8aa47c96%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C0%7C637974736319097131%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eaZFSVSuVXnyBAsbYa6jkuMltAFSQHct1OP8XQAARJI%3D&reserved=0> There are some "not as clearly labeled" portions in triplex_node that still need removing (associated with the deprecated published properties being removed). They are flagged by comment blocks with "deprecated" in the text. Theoretically, they can just be deleted. I can potentially take a look at it later this morning if they are getting a bit too far into the weeds.

**Comment by ftuffner** [comment]
@trevorhardy Was this a delayed response message?  The original was sent August 30 and we've revisited it a couple times since then.  I just wanted to make sure this wasn't another set we missed.

**Comment by trevorhardy** [comment]
I have no idea where that came from; I don't recall responding to that email yesterday but who knows. No action needed by anybody at this time.

**Pull request merged**
